# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MutationAndCodeCoverage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clean install
        run: mvn clean install
      - name: Archive code coverage - Inventory
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage-inventory
          path: inventory/target/site/jacoco
      - name: Archive mutation coverage - Inventory
        uses: actions/upload-artifact@v2
        with:
          name: mutationCoverage-inventory
          path: inventory/target/pit-reports
      - name: Archive code coverage - Shop
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage-shop
          path: shop/target/site/jacoco
      - name: Archive mutation coverage - Shop
        uses: actions/upload-artifact@v2
        with:
          name: mutationCoverage-shop
          path: shop/target/pit-reports



