# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ReleaseProcess

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]

jobs:
  quality-metrics:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven clean install
        run: mvn clean install
      - name: Mutation tests for shop module
        run: mvn -f shop/ pitest:mutationCoverage
      - name: Mutation tests for inventory module
        run: mvn -f inventory/ pitest:mutationCoverage
      - name: Archive code coverage - Inventory
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage-inventory
          path: inventory/target/site/jacoco
      - name: Archive mutation coverage - Inventory
        uses: actions/upload-artifact@v2
        with:
          name: mutationCoverage-inventory
          path: inventory/target/pit-reports
      - name: Archive code coverage - Shop
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage-shop
          path: shop/target/site/jacoco
      - name: Archive mutation coverage - Shop
        uses: actions/upload-artifact@v2
        with:
          name: mutationCoverage-shop
          path: shop/target/pit-reports

  docker-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven clean install
        run: mvn clean install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push - inventory
        uses: docker/build-push-action@v2
        with:
          context: .
          file: inventory/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ecommerceapp/inventory:latest
      - name: Build and push - shop
        uses: docker/build-push-action@v2
        with:
          context: ./shop
          file: ./shop/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ecommerceapp/shop:latest


